on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/4ec0f863ab7ce83bc572cdcdc3c65c65
          gist_title: Pr치ctica-17 DS18B20 4550-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/4550/DS18B20.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/c71c8ad00d895c815ce4feb83eb5748e
          gist_title: Pr치ctica-17 DS18B20 45K50-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/45K50/DS18B20.c
          file_encoding: WINDOWS-1252